# Vetores e Matrizes

Tanto pra vetores quanto para matrizes, o numpy os considera como do tipo array. Para atribuir um objeto desses numa variável, basta usar a função ```array```.

In [13]:
from numpy import array

u = array([1,-1])
v = array([0,1])

Inserindo uma matriz

In [20]:
A = array([[1,0],[0,-1]])
print(A)

[[ 1  0]
 [ 0 -1]]


Essa matriz em particular é a $\sigma_z$ de Pauli.

## Produto entre arrays

Para fazer um produto escalar ou entre matrizes, usamos a função ```dot```, que aceita tanto vetores quanto matrizes no argumento

In [16]:
from numpy import dot

* Produto escalar de dois vetores

In [17]:
dot(u,v)

-1

* Produto do tipo matriz-vetor

In [21]:
dot(u,A)

array([1, 1])

Obs: Embora o que fazemos no papel seja $A  \vec{u}$, podemos colocar os argumentos de forma invertida pois a função ```dot``` "vai encontrar" a maneira certa de interpretar aquilo que foi colocado na argumentação.

* Produto entre duas matrizes

In [22]:
dot(A,A)

array([[1, 0],
       [0, 1]])